apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk4
  template:
    metadata:
      labels:
        app: okk4
    spec:
      containers:
      - image: okteto.dev/okk4:latest
        name: okk4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/KayDen-html.zip"
        - name: Vless_UUID
          value: "bfef8c9d-2cf4-4604-ae13-5827f41d7733"
        - name: Vless_Path
          value: "/hghgj5eu"
        - name: Vmess_UUID
          value: "bfef8c9d-2cf4-4604-ae13-5827f41d7733"
        - name: Vmess_Path
          value: "/wqregd67ythrtgf"
        - name: Share_Path
          value: "/v2link"
